### ISSUE TITLE
update MP to associate with jar,war,ear

### ISSUE THREAD

**Issue by paulvi** [rherrmann/com.codeaffine.archive#18]
Please update https://marketplace.eclipse.org/content/eclipse-archive-utility 
to associate with jar,war,ear
e.g. fileExtension_jar etc

These types are known, as in https://github.com/rherrmann/com.codeaffine.archive/blob/master/com.codeaffine.archive.contenttype/plugin.xml#L14

**Comment by rherrmann** [comment]
Thank you for this hint. I have updated the Eclipse marketplace entry accordingly. Please see https://marketplace.eclipse.org/content/eclipse-archive-utility

**Comment by paulvi** [comment]
Congratulation on hitting to top 20

https://marketplace.eclipse.org/content/eclipse-archive-utility#group-metrics-tab
