### ISSUE TITLE
Support copy/paste of files

### ISSUE THREAD

**Issue by jochenw** [rherrmann/com.codeaffine.archive#20]
In the project explorer, I open an archive, and go to a directory. Now, if I do a right click on a file, I get the items "Open", and "Extract". I'd expect to see "Copy". Granted, "Extract" allows me to copy the file out of the directory just as well, but I wasn't expecting a folder structure below the target directory. Additionally,
Copy/Paste is such a simple, and universal usage pattern. Would be nice to have it.

**Comment by rherrmann** [comment]
I am afraid, it seems not possible to intercept the _Paste_ command to handle custom clipboard data types, like an imaginary `archive-entry-data` with contents like `archive:/path/to/archive.zip!/path/to/entry`. Not in the _Project Explorer_ view, leave alone other less generic resource-navigation views like JDT's _Package Explorer_.

Please reopen if someone knows how to create workspace resources from a custom URL. I am willing to experiment with other ideas as well, to some extent.
