### ISSUE TITLE
Enable opening archive in other views

### ISSUE THREAD

**Issue by jochenw** [rherrmann/com.codeaffine.archive#21]
Reading the plugins documentation on the homepage, I understand that I have to use the "Project Explorer" to open archive files. On the other hand, that is unlucky, because I have bo other reason to use that view. The "Package", and "Navigator" views are open all the time. Would be nice, if you could enable the archive utility in those views, too.

**Comment by rherrmann** [comment]
The _Project Explorer_ is the only view in Eclipse that allows external plug-ins to contribute elements to the tree. _Package Explorer_ and _Navigator_ do not allow for such contributions.

There is a long standing feature request to enhance the Project Explorer such that it can replace the various other explorer views [1]. I think your best bet is to hope that this issue will eventually be resolved. 

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=427897
