### ISSUE TITLE
Archive Plugin not installable via Marketplace

### ISSUE THREAD

**Issue by jochenw** [rherrmann/com.codeaffine.archive#22]
Just to make you aware of this:

    https://bugs.eclipse.org/bugs/show_bug.cgi?id=545780

(If it isn't asking too much: A downloadable installation archive would be nice. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=322335 for that.)

**Comment by paulvi** [comment]
@jochenw Do you need Eclipse feature,  
or additional distribution of particular this plugin?

**Comment by jochenw** [comment]
@paulvi I'd like to install the plugin into an Eclipse installation offline.

**Comment by paulvi** [comment]
Then you need copy of update site (aka p2 repository) as folder or zip file.

It available as https://github.com/rherrmann/com.codeaffine.archive/tree/gh-pages/repository

You can git clone , change to `gh-pages` branch, and the `repository` folder content is p2 site you can use for offline installation.
You can zip it for easier copying and install from zip file as well.

**Comment by rherrmann** [comment]
Each plug-in that is published on the marketplace needs to specify which Eclipse versions it supports. The Archive utilities marketplace entry wasn't updated for a while which I've done now.

You should see the Archive utilities entry again.

Note that you can also install the plug-in from this software site:  http://rherrmann.github.io/com.codeaffine.archive/repository

Please re-open if you still have problems installing the plug-in from the marketplace.
